test-pod.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: rachitsrivastava007/sleep:8
        ports:
        - containerPort: 80
        args:
            - -c
            - while true; do echo hello; sleep 10;done
        command:
            - /bin/sh

